name: Release tasks

on:
  release:
    types:
      - published

jobs:
  attach_theme_files:
    name: Attach theme files to release
    runs-on: "ubuntu-latest"
    env:
      release_dir_path: "./release_files"
      tdesktop_theme_path: "./TDesktop/DarkShell.tdesktop-theme"
      android_theme_path: "./Android/DarkShell.attheme"
      ios_theme_path: "./iOS/DarkShell.tgios-theme"
      macos_theme_path: "./macOS/DarkShell.palette"

    steps:
      - uses: actions/checkout@v3

      - name: Prepare fs
        run: mkdir $release_dir_path

      - name: Move files
        run: |
          mv -v -t $release_dir_path $tdesktop_theme_path $android_theme_path $ios_theme_path $macos_theme_path

      - name: Attach to release
        uses: AButler/upload-release-assets@v2.0.2

        with:
          files: "${{ env.release_dir_path }}/*"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
